2_1_model_attributes
thinknetica-django-lab-02/Uzatte pull request #13
Opened 2021-03-24 12:18 UTC by Uzatte

closes #4

2021-03-25 10:29 UTC, mikhailborodin requested changes

2021-03-25 10:29 UTC, mikhailborodin commented on main/main/models.py
> +    categories = models.ManyToManyField(Category)
для проекта лучше сделать так, чтобы товар мог находиться только в одной категории

2021-03-25 10:29 UTC, mikhailborodin commented on main/main/models.py
> +    tags = models.ManyToManyField(Tag)
зачем продавцу тэги?

2021-03-25 10:29 UTC, mikhailborodin commented on main/main/models.py
> +    goods = models.ManyToManyField(Good)
у товара может быть только один продавец, поэтому внешний ключ на продавца должен быть у товара

2021-03-25 18:17 UTC, Uzatte commented on main/main/models.py
> +    categories = models.ManyToManyField(Category)
Изменил.

2021-03-25 18:19 UTC, Uzatte commented on main/main/models.py
> +    tags = models.ManyToManyField(Tag)
Изначально предполагал, что это будет торговая большая торговая площадка с множеством продавцов. Для упрощения навигации думал тоже навесить на них тэги. Например, можно выбрать всех продавцов с тэгов "электроника".  Но сейчас подумал и да, в прицнипе они не особо нужны.

2021-03-25 18:21 UTC, Uzatte commented on main/main/models.py
> +    goods = models.ManyToManyField(Good)
Опять таки, изначально предполагал, что это торговая площадка. где продают абстрактные товары. В таком случае, есть карточка товара, в которой может отображаться список продавцов, готовых этот товар продать. 
Исправил.

2021-03-26 10:00 UTC, mikhailborodin approved these changes

2021-03-26 10:28 UTC, merged