2_3_change_model
thinknetica-django-lab-02/Uzatte pull request #15
Opened 2021-03-24 17:08 UTC by Uzatte

closes #2

2021-03-25 10:30 UTC, mikhailborodin requested changes

2021-03-25 10:30 UTC, mikhailborodin commented on main/main/models.py
> +    manufacturer = models.CharField('Производитель товара', max_length=120)
с производителем тоже через внешний ключ нужно установить связь

2021-03-25 18:34 UTC, Uzatte commented on main/main/models.py
> +    manufacturer = models.CharField('Производитель товара', max_length=120)
Добавил модель данных для производителя и установил в товара связь с ним через внешний ключ.

2021-03-26 10:01 UTC, mikhailborodin approved these changes

2021-03-26 10:24 UTC, merged