3_5_filtering_and_pagination
thinknetica-django-lab-02/Uzatte pull request #28
Opened 2021-03-29 11:09 UTC by Uzatte

closes #19

2021-03-30 08:50 UTC, mikhailborodin requested changes

2021-03-30 08:50 UTC, mikhailborodin commented on main/main/templates/main/good_list.html
> +            <td><a href = "{% url 'goods' %}{{ good.id }}/"> {{ good.name }} </a> </td>
правильнее использовать `{% url 'good-detail' good.id %}`

2021-03-30 08:50 UTC, mikhailborodin commented on main/main/urls.py
>      path('goods/<pk>/', views.GoodDetail.as_view()),
и сюда надо добавить `name='good-detail'`

2021-03-30 12:45 UTC, Uzatte commented on main/main/templates/main/good_list.html
> +            <td><a href = "{% url 'goods' %}{{ good.id }}/"> {{ good.name }} </a> </td>
Исправил

2021-03-30 12:45 UTC, Uzatte commented on main/main/urls.py
>      path('goods/<pk>/', views.GoodDetail.as_view()),
Добавил

2021-03-31 08:12 UTC, mikhailborodin approved these changes

2021-03-31 08:51 UTC, merged