4_3_form_validation
thinknetica-django-lab-02/Uzatte pull request #30
Opened 2021-03-29 20:15 UTC by Uzatte

Closes #17

2021-03-30 08:52 UTC, mikhailborodin requested changes

2021-03-30 08:52 UTC, mikhailborodin commented on main/main/models.py
> +    first_name = models.CharField('Имя пользователя', max_length=120)
эти поля есть в модели User, тут их не надо дублировать

2021-03-30 18:34 UTC, Uzatte commented on main/main/models.py
> +    first_name = models.CharField('Имя пользователя', max_length=120)
Убрал эти поля из модели Profile.

2021-03-31 08:49 UTC, mikhailborodin approved these changes

2021-04-02 04:32 UTC, merged