5_3_groups_of_users
thinknetica-django-lab-02/Uzatte pull request #45
Opened 2021-04-05 13:16 UTC by Uzatte

closes #41

2021-04-06 12:25 UTC, mikhailborodin requested changes

2021-04-06 12:25 UTC, mikhailborodin commented on main/main/models.py
> +            instance.groups.add(Group.objects.get(name='common users'))
если группа не создана, то будет ошибка

2021-04-06 14:38 UTC, Uzatte commented on main/main/models.py
> +            instance.groups.add(Group.objects.get(name='common users'))
Добавил блок Try-Except для контроля исключения Group.DoesNotExist. Здесь сделал просто print в консоль, а в реальном проекте можно сделать либо запись в лог, либо отослать сообщение администратору через telegram или email, т..к. ситуация, при которой на сайте отсутствует группа, которая является дефолтовой для всех новых пользователей явно исключительная.

2021-04-07 09:33 UTC, mikhailborodin commented on main/main/models.py
> +            instance.groups.add(Group.objects.get(name='common users'))
лучше использовать get_or_create

2021-04-07 09:35 UTC, mikhailborodin requested changes

2021-04-07 09:35 UTC, mikhailborodin commented on main/main/models.py
> +                print("Group Doesn't Exist")
если группы нет, то её надо создать

2021-04-07 09:56 UTC, Uzatte commented on main/main/models.py
> +            instance.groups.add(Group.objects.get(name='common users'))
Понял, спасибо! Исправил.

2021-04-08 09:02 UTC, mikhailborodin approved these changes

2021-04-08 10:04 UTC, merged