6_3_distribution_list
thinknetica-django-lab-02/Uzatte pull request #50
Opened 2021-04-06 08:07 UTC by Uzatte

closes #37

2021-04-09 09:58 UTC, mikhailborodin requested changes

2021-04-09 09:58 UTC, mikhailborodin commented on main/main/models.py
> +    user = models.ManyToManyField(User)
можно и так, но так будет сложнее добавлять новых подписчиков. То есть чтобы добавить подписчика, вам надо будет найти какую-либо подписку, потом сделать вставку. А если делать OneToOneField то искать ничего не надо, просто делаете вставку

2021-04-09 09:59 UTC, mikhailborodin requested changes

2021-04-09 09:59 UTC, mikhailborodin commented on main/main/models.py
> +            mail.send_mail(subject, plain_message, from_email, [to],
можно сразу список мэйлов вставлять в этот метод, а значит цикл не нужен

2021-04-10 07:10 UTC, Uzatte commented on main/main/models.py
> +    user = models.ManyToManyField(User)
Сделал связь 1 к 1.

2021-04-10 07:11 UTC, Uzatte commented on main/main/models.py
> +            mail.send_mail(subject, plain_message, from_email, [to],
Деперсонифицировал  рассылку и убрал цикл.

2021-04-10 14:23 UTC, mikhailborodin approved these changes

2021-04-10 15:32 UTC, merged